version: '1.4'
services:
  middelware:
    image: chenqueta_middelware:2.0
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: chenqueta_middelware
    volumes:
      - .:/usr/src/app/
    command: python middelware.py
    
  web:
    depends_on:
      - middelware
    image: chenqueta_web:4.0
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: chenqueta_web
    volumes:
      - .:/usr/src/app/
    ports: 
      - 80:80
    command: streamlit run main.py --server.port 80
