version: '1.3'
services:
  backend:
    image: chenqueta_backend:2.0
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: chenqueta_backend
    volumes:
      - shared-files:/usr/src/app/shared/
      # - .:/usr/src/app/
    command: python backend.py
    
  frontend:
    depends_on:
      - backend
    image: chenqueta_frontend:4.0
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: chenqueta_frontend
    volumes:
      - shared-files:/usr/src/app/shared/ 
      # - .:/usr/src/app/
    ports: 
      - 8501:8501
    command: streamlit run main.py

volumes:
  shared-files: