version: '1.2'
services:
  backend:
    build: ./
    container_name: chenqueta_backend
    volumes:
      - ./:/usr/src/app/:rw
    command: python backend.py
    
  frontend:
    build: ./
    container_name: chenqueta_frontend
    volumes:
      - ./:/usr/src/app/:rw
    ports: 
      - 8501:8501
    command: streamlit run main.py