version: '1.5'
services:
  middleware:
    image: chengeta_middleware:2.0
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: chengeta_middleware
    volumes:
      - .:/usr/src/app/
    command: python middleware.py
    
  web:
    depends_on:
      - middleware
    image: chengeta_web:4.0
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: chengeta_web
    volumes:
      - .:/usr/src/app/
    ports: 
      - 80:80
    command: streamlit run main.py --server.port 80

  garbage-collector:
    depends_on:
      - middleware
    image: chengeta_garbage-collector:1.0
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: chengeta_garbage-collector
    volumes:
      - .:/usr/src/app/
    command: python garbage-collector.py