version: '1.3'
services:
  backend:
    image: chenqueta_backend:2.0
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: chenqueta_backend
    volumes:
      - .:/usr/src/app/
    command: python backend.py
    
  frontend:
    depends_on:
      - backend
    image: chenqueta_frontend:4.0
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: chenqueta_frontend
    volumes:
      - .:/usr/src/app/
    ports: 
      - 80:80
    command: streamlit run main.py --server.port 80
