version: '1.4'
services:
  middleware:
    image: chenqueta_middleware:2.0
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: chenqueta_middleware
    volumes:
      - .:/usr/src/app/
    command: python middleware.py
    
  web:
    depends_on:
      - middleware
    image: chenqueta_web:4.0
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: chenqueta_web
    volumes:
      - .:/usr/src/app/
    ports: 
      - 80:80
    command: streamlit run main.py --server.port 80
